CREATE TABLE [dbo].[CRMPartner] (
    [CRMPartnerId]           INT            IDENTITY (1, 1) NOT NULL,
    [AccountId]              NVARCHAR (100) NOT NULL,
    [Partnertype]            NVARCHAR (100) NULL,
    [MembershipType]         NVARCHAR (100) NULL,
    [PartnerName]            NVARCHAR (200) NULL,
    [CVR]                    NVARCHAR (255) NULL,
    [Telefon]                NVARCHAR (50)  NULL,
    [Centertype]             NVARCHAR (100) NULL,
    [Address1]               NVARCHAR (500) NULL,
    [Address2]               NVARCHAR (500) NULL,
    [Town]                   NVARCHAR (200) NULL,
    [PostNumber]             NVARCHAR (100) NULL,
    [Land]                   NVARCHAR (200) NULL,
    [StateAgreement]         BIT            NULL,
    [Debitornummer]          NVARCHAR (100) NULL,
    [Debitornummer2]         NVARCHAR (100) NULL,
    [Regions]                NVARCHAR (500) NULL,
    [MembershipStartDate]    DATETIME       NULL,
    [PublicURL]              NVARCHAR (500) NULL,
    [Email]                  NVARCHAR (100) NULL,
    [Website]                NVARCHAR (200) NULL,
    [PanoramView]            NVARCHAR (200) NULL,
    [RecommandedNPGRT60]     BIT            NULL,
    [QualityAssuredNPSGRD30] BIT            NULL,
    [LastModified]           DATETIME       NULL,
    [LastModifiedBy]         NVARCHAR (100) NULL,
    [CreatedDate]            DATETIME       NULL,
    [CreatedBy]              NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([CRMPartnerId] ASC),
    UNIQUE NONCLUSTERED ([AccountId] ASC)
);


