CREATE TABLE [dbo].[Procedure]
(
	[ProcedureId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ProcedureTitle] VARCHAR(255) NOT NULL, 
    [BookingId] INT NOT NULL,
	[ProcedureReviewTypeId] INT NOT NULL,
	[PartnerEmployeeId] INT NULL,
	[PartnerId] INT NOT NULL,
	[SRCommunicationId] INT NULL,
	[CustomerId] INT NOT NULL,
	[ContactId] INT NULL,
	[ProcedureCancelReasonId] INT NULL,
	[CauseOfRemovalId] INT NOT NULL,
	[ProcedureReplyId] INT NULL,
	[UsedInEmailOffer] BIT NULL,
	[TurnOffNotification] BIT NULL,
	[ProcedureSharePointId] INT NULL,
	[IndustryCode] NVARCHAR NULL,
	[ProcedureStatusId] INT NULL,
	[TotalPrice] INT NULL,
    [LastModified] DATETIME NOT NULL, 
    [LastModifiedBY] NVARCHAR(255) NOT NULL,
	[CreatedDate] DATETIME NULL,
	[CreatedBy] nvarchar(100),
    CONSTRAINT [FK_Procedures_Booking] FOREIGN KEY (BookingId) REFERENCES Booking(BookingId), 
    CONSTRAINT [FK_Procedures_Partner] FOREIGN KEY (PartnerId) REFERENCES Partner(PartnerId), 
    CONSTRAINT [FK_Procedures_Customer] FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId), 
    CONSTRAINT [FK_Procedures_CauseOfRemoval] FOREIGN KEY (CauseOfRemovalId) REFERENCES CauseOfRemoval(CauseOfRemovalId), 
    CONSTRAINT [FK_Procedures_ProcedureReviewType] FOREIGN KEY (ProcedureReviewTypeId) REFERENCES ProcedureReviewType(ProcedureReviewTypeId),
	CONSTRAINT [FK_Procedures_SRCommunication] FOREIGN KEY (SRCommunicationId) REFERENCES ServiceRequestCommunication(ServiceRequestCommunicationId),
	CONSTRAINT [FK_Procedures_PartnerEmployee] FOREIGN KEY (PartnerEmployeeId) REFERENCES PartnerEmployee(PartnerEmployeeId),
	CONSTRAINT [FK_Procedures_ContactPerson] FOREIGN KEY (ContactId) REFERENCES ContactPerson(ContactPersonId),
	CONSTRAINT [FK_Procedures_ProcedureCancelReason] FOREIGN KEY (ProcedureCancelReasonId) REFERENCES ProcedureCancelReason(ProcedureCancelReasonId),
	CONSTRAINT [FK_Procedures_ProcedureReply] FOREIGN KEY (ProcedureReplyId) REFERENCES ProcedureReply(ProcedureReplyId),
	CONSTRAINT [FK_Procedures_ProcedureStatus] FOREIGN KEY (ProcedureStatusId) REFERENCES ProcedureStatus(ProcedureStatusId),
)
